### ISSUE TITLE
Could you port to 1.18.2 and use WTHIT/JADE as a base?

### ISSUE THREAD

**Issue by DarthCaesium** [Darkhax-Minecraft/WAWLA#158]
It would be really sad to see WAWLA not existing anymore, and seeing that Hwyla will no longer be updated, this means that without endorsing one of or both of these two, WAWLA cannot be updated. I'd love to be able to continue using WAWLA, as it's really useful.

**Comment by Darkhax** [comment]
Hello, 

Yes, I am planning to update WAWLA to newer versions eventually, however I have no intention of using JADE or WTHIT as a base. The plan is for WAWLA to become it's own "information engine" as a base moving forward. This has been the plan since 1.9 however I put this on hold when Hwyla came out.

**Comment by DarthCaesium** [comment]
Thank you so much

**Comment by ItsZer0here** [comment]
aaaaaaaaaaaaaaaand i just copied your issue.
