### ISSUE TITLE
NullPointer when removing EnderIO Energy Pipes

### ISSUE THREAD

**Issue by knoxz** [Darkhax-Minecraft/WAWLA#47]
Hi there,

Using latest WAWLA on 1.9.4.
Every third Energy Conduit I remove crashes my client. Tried Wrench or pickaxe. Same result.
You might wanna catch this exception and display an error or maybe nothing at all as it happens right on the transition.

http://pastebin.com/WGLpCCry

**Comment by darkhax** [comment]
The code that is crashing you suggests that this is actually an issue with EnderIO or perhaps vanilla. Regardless this entire section of code related was removed a few hours ago. https://github.com/Darkhax-Minecraft/WAWLA/commit/373f5f37aa65727d581eef2ea9e27555650cdb86

**Comment by knoxz** [comment]
The way I see it wawla tries to pull data from an entity that isnt there anymore.
Thats why the crash happens when removing conduits.
Also even if the error is on their side for returning null for some reason, it would still be an easy fix on your side.

But if it is already resolved its fine I guess. is the new version on curse already?

**Comment by darkhax** [comment]
The issue is that Wawla does not grab the entity info, that is handled by Waila or ICSE. The source of this crash is likely related to a vanilla threading issue, which has been popping up a lot for other mod authors in other situations. The other possibility is that the EnderIO conduit has a bug in their code that gets the item form of the conduit, although this is much less likely. 

My solution to the issue was to remove the line of code from wawla that was causing this crash. The underlying issue is still there, although if it is a thread issue it may be harder to reproduce because the timing will be a few nanoseconds different. 

Anyhow, the new version is up on CurseForge. All of my mods now automatically release a new alpha build to CurseForge when I change something on GitHub.
