### ISSUE TITLE
Crash on pressing f3 button.

### ISSUE THREAD

**Issue by varukasalt** [Darkhax-Minecraft/WAWLA#51]
Wawla-1.10.2-2.3.0.200

Game closing crash when f3 button is pressed. 100% repeatable. Reverting to Wawla-1.10.2-2.3.0.193 (last one I had on hand) resolves this. 

Crash report

http://pastebin.com/MSPx11Mi

**Comment by DatrixTHLK** [comment]
I can confirm this also

Wawla: 1.2.3.0.200
Minecraft 1.10.2
forge: 12.18.1.2043
Crash Report: http://pastebin.com/HLLsXJ5r

**Comment by darkhax** [comment]
Thank you for reporting this issue. It's weird that reverting to build 192 would fix this issue, as the code related hasn't changed since may 30th which is long before either build was released. I suspect that another mod may be messing with the f3 debug list. Going to push a new version in a few minutes that should fix this.

**Comment by DatrixTHLK** [comment]
Sure thing DarkHax

**Comment by darkhax** [comment]
Due to no response, I am considering this issue fixed. If that is not the case, please let me know.
